<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonLogin</name>
   <tag></tag>
   <elementGuidId>b4b435f9-8b39-4df2-a78a-c44ac8ad0c35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;hg&quot;]/div/div/div/div[2]/form/div/div/div[4]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;hg&quot;]/div/div/div/div[2]/form/div/div/div[4]/div/button</value>
   </webElementProperties>
</WebElementEntity>
