<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonEdit</name>
   <tag></tag>
   <elementGuidId>dde2f388-5555-42d6-ae11-7c29c54aa754</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;datatables&quot;]/tbody/tr[1]/td[5]/center/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;datatables&quot;]/tbody/tr[1]/td[5]/center/a[2]</value>
   </webElementProperties>
</WebElementEntity>
