<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonEdit</name>
   <tag></tag>
   <elementGuidId>6ab0ec9f-cad4-4896-9689-0faf93780bfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;datatables&quot;]/tbody/tr[1]/td[6]/center/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;datatables&quot;]/tbody/tr[1]/td[6]/center/a</value>
   </webElementProperties>
</WebElementEntity>
